#!/usr/bin/env bash

export CRAFTIVE_SECRET_KEY=super-secret-devenv-key
export CRAFTIVE_HOST=devenv
export CRAFTIVE_FLAGS="\
       $CRAFTIVE_FLAGS \
       enable-login-with-ldap \
       enable-login-with-password
       enable-login-with-oidc \
       enable-login-with-google \
       enable-login-with-github \
       enable-login-with-gitlab \
       enable-backend-worker \
       enable-backend-asserts \
       enable-feature-fdata-pointer-map \
       enable-feature-fdata-objects-map \
       enable-audit-log \
       enable-transit-readable-response \
       enable-demo-users \
       disable-secure-session-cookies \
       enable-smtp \
       enable-prepl-server \
       enable-urepl-server \
       enable-rpc-climit \
       enable-rpc-rlimit \
       enable-quotes \
       enable-soft-rpc-rlimit \
       enable-auto-file-snapshot \
       enable-webhooks \
       enable-access-tokens \
       enable-tiered-file-data-storage \
       enable-file-validation \
       enable-file-schema-validation \
       enable-subscriptions \
       enable-subscriptions-old";

# Default deletion delay for devenv
export CRAFTIVE_DELETION_DELAY="24h"

# Setup default upload media file size to 100MiB
export CRAFTIVE_MEDIA_MAX_FILE_SIZE=104857600

# Setup default multipart upload size to 300MiB
export CRAFTIVE_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE=314572800

# export CRAFTIVE_DATABASE_URI="postgresql://172.17.0.1:5432/craftive"
# export CRAFTIVE_DATABASE_USERNAME="craftive"
# export CRAFTIVE_DATABASE_PASSWORD="craftive"
# export CRAFTIVE_DATABASE_READONLY=true

# export CRAFTIVE_DATABASE_URI="postgresql://172.17.0.1:5432/craftive_pre"
# export CRAFTIVE_DATABASE_USERNAME="craftive_pre"
# export CRAFTIVE_DATABASE_PASSWORD="craftive_pre"

# export CRAFTIVE_LOGGERS_LOKI_URI="http://172.17.0.1:3100/loki/api/v1/push"
# export CRAFTIVE_AUDIT_LOG_ARCHIVE_URI="http://localhost:6070/api/audit"

# Initialize MINIO config
mc alias set craftive-s3/ http://minio:9000 minioadmin minioadmin -q
mc admin user add craftive-s3 craftive-devenv craftive-devenv -q
mc admin user info craftive-s3 craftive-devenv |grep -F -q "readwrite"
if [ "$?" = "1" ]; then
    mc admin policy attach craftive-s3 readwrite --user=craftive-devenv -q
fi
mc mb craftive-s3/craftive -p -q

export AWS_ACCESS_KEY_ID=craftive-devenv
export AWS_SECRET_ACCESS_KEY=craftive-devenv

export CRAFTIVE_OBJECTS_STORAGE_BACKEND=s3
export CRAFTIVE_OBJECTS_STORAGE_S3_ENDPOINT=http://minio:9000
export CRAFTIVE_OBJECTS_STORAGE_S3_BUCKET=craftive
export CRAFTIVE_OBJECTS_STORAGE_FS_DIRECTORY="assets"

export JAVA_OPTS="\
       -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager \
       -Djdk.attach.allowAttachSelf \
       -Dlog4j2.configurationFile=log4j2-devenv-repl.xml \
       -Djdk.tracePinnedThreads=full \
       -XX:+EnableDynamicAgentLoading \
       -XX:-OmitStackTraceInFastThrow                    \
       -XX:+UnlockDiagnosticVMOptions \
       -XX:+DebugNonSafepoints \
       --sun-misc-unsafe-memory-access=allow \
       --enable-preview \
       --enable-native-access=ALL-UNNAMED";

export OPTIONS="-A:jmx-remote -A:dev"

# Setup HEAP
# export OPTIONS="$OPTIONS -J-Xms50m -J-Xmx1024m"
# export OPTIONS="$OPTIONS -J-Xms1100m -J-Xmx1100m -J-XX:+AlwaysPreTouch"

# Increase virtual thread pool size
# export OPTIONS="$OPTIONS -J-Djdk.virtualThreadScheduler.parallelism=16"

# Disable C2 Compiler
# export OPTIONS="$OPTIONS -J-XX:TieredStopAtLevel=1"

# Disable all compilers
# export OPTIONS="$OPTIONS -J-Xint"

# Setup GC
# export OPTIONS="$OPTIONS -J-XX:+UseG1GC"

# Setup GC
# export OPTIONS="$OPTIONS -J-XX:+UseZGC"

# Enable ImageMagick v7.x support
# export OPTIONS="-J-Dim4java.useV7=true $OPTIONS";

export OPTIONS_EVAL="nil"
# export OPTIONS_EVAL="(set! *warn-on-reflection* true)"

set -ex
exec clojure $OPTIONS -M -e "$OPTIONS_EVAL" -m rebel-readline.main
