#!/usr/bin/env bash

export CRAFTIVE_SECRET_KEY=super-secret-devenv-key
export CRAFTIVE_HOST=devenv
export CRAFTIVE_FLAGS="\
       $CRAFTIVE_FLAGS \
       enable-backend-asserts \
       enable-feature-fdata-pointer-map \
       enable-feature-fdata-objects-map \
       enable-file-snapshot \
       enable-tiered-file-data-storage";

export JAVA_OPTS="
       -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager \
       -Djdk.attach.allowAttachSelf \
       -Dlog4j2.configurationFile=log4j2-devenv.xml \
       -XX:+EnableDynamicAgentLoading \
       -XX:-OmitStackTraceInFastThrow \
       -XX:+UnlockDiagnosticVMOptions \
       -XX:+DebugNonSafepoints";

export CLOJURE_OPTIONS="-A:dev"


# Default deletion delay for devenv
export CRAFTIVE_DELETION_DELAY="24h"

# Setup default upload media file size to 100MiB
export CRAFTIVE_MEDIA_MAX_FILE_SIZE=104857600

# Setup default multipart upload size to 300MiB
export CRAFTIVE_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE=314572800

export AWS_ACCESS_KEY_ID=craftive-devenv
export AWS_SECRET_ACCESS_KEY=craftive-devenv
export CRAFTIVE_OBJECTS_STORAGE_BACKEND=s3
export CRAFTIVE_OBJECTS_STORAGE_S3_ENDPOINT=http://minio:9000
export CRAFTIVE_OBJECTS_STORAGE_S3_BUCKET=craftive

entrypoint=${1:-app.main};
shift 1;
set -ex

clojure $CLOJURE_OPTIONS -A:dev -M -m $entrypoint "$@";
