#!/usr/bin/env bash

export CRAFTIVE_SECRET_KEY=super-secret-devenv-key
export CRAFTIVE_HOST=devenv
export CRAFTIVE_FLAGS="\
       $CRAFTIVE_FLAGS \
       enable-prepl-server \
       enable-urepl-server \
       enable-nrepl-server \
       enable-webhooks \
       enable-backend-asserts \
       enable-audit-log \
       enable-login-with-ldap \
       enable-transit-readable-response \
       enable-demo-users \
       enable-feature-fdata-pointer-map \
       enable-feature-fdata-objects-map \
       disable-secure-session-cookies \
       enable-rpc-climit \
       enable-smtp \
       enable-quotes \
       enable-file-snapshot \
       enable-access-tokens \
       enable-tiered-file-data-storage \
       enable-file-validation \
       enable-file-schema-validation \
       enable-subscriptions \
       enable-subscriptions-old ";

# Default deletion delay for devenv
export CRAFTIVE_DELETION_DELAY="24h"

# Setup default upload media file size to 100MiB
export CRAFTIVE_MEDIA_MAX_FILE_SIZE=104857600

# Setup default multipart upload size to 300MiB
export CRAFTIVE_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE=314572800

# Enable ImageMagick v7.x support
# export OPTIONS="-J-Dim4java.useV7=true $OPTIONS";

# Initialize MINIO config
mc alias set craftive-s3/ http://minio:9000 minioadmin minioadmin -q
mc admin user add craftive-s3 craftive-devenv craftive-devenv -q
mc admin user info craftive-s3 craftive-devenv |grep -F -q "readwrite"
if [ "$?" = "1" ]; then
    mc admin policy attach craftive-s3 readwrite --user=craftive-devenv -q
fi
mc mb craftive-s3/craftive -p -q

export AWS_ACCESS_KEY_ID=craftive-devenv
export AWS_SECRET_ACCESS_KEY=craftive-devenv
export CRAFTIVE_OBJECTS_STORAGE_BACKEND=s3
export CRAFTIVE_OBJECTS_STORAGE_S3_ENDPOINT=http://minio:9000
export CRAFTIVE_OBJECTS_STORAGE_S3_BUCKET=craftive

entrypoint=${1:-app.main};

export JAVA_OPTS="\
       -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager \
       -Djdk.attach.allowAttachSelf \
       -Dlog4j2.configurationFile=log4j2-devenv.xml \
       -Djdk.tracePinnedThreads=full \
       -XX:+EnableDynamicAgentLoading \
       -XX:-OmitStackTraceInFastThrow                    \
       -XX:+UnlockDiagnosticVMOptions \
       -XX:+DebugNonSafepoints \
       --sun-misc-unsafe-memory-access=allow \
       --enable-preview \
       --enable-native-access=ALL-UNNAMED";

export OPTIONS="-A:jmx-remote -A:dev"

set -ex
clojure $OPTIONS -M -m $entrypoint;
