## Common flags:
# demo-users
# email-verification
# log-emails
# log-invitation-tokens
# login-with-github
# login-with-gitlab
# login-with-google
# login-with-ldap
# login-with-oidc
# login-with-password
# prepl-server
# registration
# secure-session-cookies
# smtp
# smtp-debug
# telemetry
# webhooks
##
## You can read more about all available flags and other
## environment variables here:
## https://help.craftive.app/technical-guide/configuration/#advanced-configuration
#
# WARNING: if you're exposing Craftive to the internet, you should remove the flags
# 'disable-secure-session-cookies' and 'disable-email-verification'
x-flags: &craftive-flags
  CRAFTIVE_FLAGS: disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies

x-uri: &craftive-public-uri
  CRAFTIVE_PUBLIC_URI: http://localhost:9001

x-body-size: &craftive-http-body-size
  # Max body size (30MiB); Used for plain requests, should never be
  # greater than multi-part size
  CRAFTIVE_HTTP_SERVER_MAX_BODY_SIZE: 31457280

  # Max multipart body size (350MiB)
  CRAFTIVE_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE: 367001600


networks:
  craftive:

volumes:
  craftive_postgres_v15:
  craftive_assets:
  # craftive_traefik:
  # craftive_minio:

services:
  ## Traefik service declaration example. Consider using it if you are going to expose
  ## craftive to the internet, or a different host than `localhost`.

  # traefik:
  #   image: traefik:v3.3
  #   networks:
  #     - craftive
  #   command:
  #     - "--api.insecure=true"
  #     - "--entryPoints.web.address=:80"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entryPoints.websecure.address=:443"
  #     - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
  #     - "--certificatesresolvers.letsencrypt.acme.email=<EMAIL_ADDRESS>"
  #     - "--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json"
  #   volumes:
  #     - "craftive_traefik:/traefik"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   ports:
  #     - "80:80"
  #     - "443:443"

  craftive-frontend:
    image: "craftiveapp/frontend:${CRAFTIVE_VERSION:-latest}"
    restart: always
    ports:
      - 9001:8080

    volumes:
      - craftive_assets:/opt/data/assets

    depends_on:
      - craftive-backend
      - craftive-exporter

    networks:
      - craftive

    # labels:
      # - "traefik.enable=true"

      # ## HTTPS: example of labels for the case where craftive will be exposed to the
      # ## internet with HTTPS using traefik.

      # - "traefik.http.routers.craftive-https.rule=Host(`<DOMAIN_NAME>`)"
      # - "traefik.http.routers.craftive-https.entrypoints=websecure"
      # - "traefik.http.routers.craftive-https.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.craftive-https.tls=true"

    environment:
      << : [*craftive-flags, *craftive-http-body-size]

  craftive-backend:
    image: "craftiveapp/backend:${CRAFTIVE_VERSION:-latest}"
    restart: always

    volumes:
      - craftive_assets:/opt/data/assets

    depends_on:
      craftive-postgres:
        condition: service_healthy
      craftive-redis:
        condition: service_healthy

    networks:
      - craftive

    ## Configuration envronment variables for the backend container.

    environment:
      << : [*craftive-flags, *craftive-public-uri, *craftive-http-body-size]

      ## Craftive SECRET KEY. It serves as a master key from which other keys for subsystems
      ## (eg http sessions, or invitations) are derived.
      ##
      ## If you leave it commented, all created sessions and invitations will
      ## become invalid on container restart.
      ##
      ## If you going to uncomment this, we recommend to use a trully randomly generated
      ## 512 bits base64 encoded string here.  You can generate one with:
      ##
      ## python3 -c "import secrets; print(secrets.token_urlsafe(64))"

      # CRAFTIVE_SECRET_KEY: my-insecure-key

      ## The PREPL host. Mainly used for external programatic access to craftive backend
      ## (example: admin). By default it will listen on `localhost` but if you are going to use
      ## the `admin`, you will need to uncomment this and set the host to `0.0.0.0`.

      # CRAFTIVE_PREPL_HOST: 0.0.0.0

      ## Database connection parameters. Don't touch them unless you are using custom
      ## postgresql connection parameters.

      CRAFTIVE_DATABASE_URI: postgresql://craftive-postgres/craftive
      CRAFTIVE_DATABASE_USERNAME: craftive
      CRAFTIVE_DATABASE_PASSWORD: craftive

      ## Redis is used for the websockets notifications. Don't touch unless the redis
      ## container has different parameters or different name.

      CRAFTIVE_REDIS_URI: redis://craftive-redis/0

      ## Default configuration for assets storage: using filesystem based with all files
      ## stored in a docker volume.

      CRAFTIVE_ASSETS_STORAGE_BACKEND: assets-fs
      CRAFTIVE_STORAGE_ASSETS_FS_DIRECTORY: /opt/data/assets

      ## Also can be configured to to use a S3 compatible storage
      ## service like MiniIO. Look below for minio service setup.

      # AWS_ACCESS_KEY_ID: <KEY_ID>
      # AWS_SECRET_ACCESS_KEY: <ACCESS_KEY>
      # CRAFTIVE_ASSETS_STORAGE_BACKEND: assets-s3
      # CRAFTIVE_STORAGE_ASSETS_S3_ENDPOINT: http://craftive-minio:9000
      # CRAFTIVE_STORAGE_ASSETS_S3_BUCKET: <BUKET_NAME>

      ## Telemetry. When enabled, a periodical process will send anonymous data about this
      ## instance. Telemetry data will enable us to learn how the application is used,
      ## based on real scenarios. If you want to help us, please leave it enabled. You can
      ## audit what data we send with the code available on github.

      CRAFTIVE_TELEMETRY_ENABLED: true
      CRAFTIVE_TELEMETRY_REFERER: compose

      ## Example SMTP/Email configuration. By default, emails are sent to the mailcatch
      ## service, but for production usage it is recommended to setup a real SMTP
      ## provider. Emails are used to confirm user registrations & invitations. Look below
      ## how the mailcatch service is configured.

      CRAFTIVE_SMTP_DEFAULT_FROM: no-reply@example.com
      CRAFTIVE_SMTP_DEFAULT_REPLY_TO: no-reply@example.com
      CRAFTIVE_SMTP_HOST: craftive-mailcatch
      CRAFTIVE_SMTP_PORT: 1025
      CRAFTIVE_SMTP_USERNAME:
      CRAFTIVE_SMTP_PASSWORD:
      CRAFTIVE_SMTP_TLS: false
      CRAFTIVE_SMTP_SSL: false

  craftive-exporter:
    image: "craftiveapp/exporter:${CRAFTIVE_VERSION:-latest}"
    restart: always

    depends_on:
      craftive-redis:
        condition: service_healthy

    networks:
      - craftive

    environment:
      # Don't touch it; this uses an internal docker network to
      # communicate with the frontend.
      CRAFTIVE_PUBLIC_URI: http://craftive-frontend:8080

      ## Redis is used for the websockets notifications.
      CRAFTIVE_REDIS_URI: redis://craftive-redis/0

  craftive-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U craftive"]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 2s

    volumes:
      - craftive_postgres_v15:/var/lib/postgresql/data

    networks:
      - craftive

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=craftive
      - POSTGRES_USER=craftive
      - POSTGRES_PASSWORD=craftive

  craftive-redis:
    image: redis:7.2
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 3s

    networks:
      - craftive

  ## A mailcatch service, used as temporal SMTP server. You can access via HTTP to the
  ## port 1080 for read all emails the craftive platform has sent. Should be only used as a
  ## temporal solution while no real SMTP provider is configured.

  craftive-mailcatch:
    image: sj26/mailcatcher:latest
    restart: always
    expose:
      - '1025'
    ports:
      - "1080:1080"
    networks:
      - craftive

  ## Example configuration of MiniIO (S3 compatible object storage service); If you don't
  ## have preference, then just use filesystem, this is here just for the completeness.

  # minio:
  #   image: "minio/minio:latest"
  #   command: minio server /mnt/data --console-address ":9001"
  #   restart: always
  #
  #   volumes:
  #     - "craftive_minio:/mnt/data"
  #
  #   environment:
  #     - MINIO_ROOT_USER=minioadmin
  #     - MINIO_ROOT_PASSWORD=minioadmin
  #
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
