FROM nginxinc/nginx-unprivileged:1.28.0
LABEL maintainer="Craftive <docker@craftive.app>"

USER root

RUN set -ex; \
    useradd -U -M -u 1001 -s /bin/false -d /opt/craftive craftive; \
    mkdir -p /opt/data/assets; \
    chown -R craftive:craftive /opt/data;

ADD ./bundle-frontend/ /var/www/app/
ADD ./files/config.js /var/www/app/js/config.js
ADD ./files/nginx.conf /etc/nginx/nginx.conf.template
ADD ./files/nginx-proxies.conf /etc/nginx/nginx-proxies.conf
ADD ./files/resolvers.conf /etc/nginx/overrides.d/resolvers.conf.template
ADD ./files/nginx-mime.types /etc/nginx/mime.types
ADD ./files/nginx-entrypoint.sh /entrypoint.sh

RUN chown -R 1001:0 /var/cache/nginx; \
    chmod -R g+w /var/cache/nginx; \
    chown -R 1001:0 /etc/nginx; \
    chmod -R g+w /etc/nginx; \
    chown -R 1001:0 /var/www; \
    chmod -R g+w /var/www;

USER craftive:craftive
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
